import { Card } from '@/types/card';

export const mockCards: Card[] = [
    {
        id: 1,
        title: '같이 공연 가요',
        location: '부산',
        date: Date.now() + 1000 * 60 * 60 * 24 * 7,
        deadline: Date.now() + 1000 * 60 * 60 * 24 * 5,
        currentPerson: 1,
        maxPerson: 3,
        openStatus: 'waiting',
        wishList: false,
        image: '/images/Rectangle 6189.svg',
        createdUser: '김철수',
        createdUserProfileImg: '',
    },
    {
        id: 2,
        title: '같이 공연 가요',
        location: '부산',
        date: Date.now() + 1000 * 60 * 60 * 24 * 7,
        deadline: Date.now() + 1000 * 60 * 60 * 24 * 5,
        currentPerson: 1,
        maxPerson: 3,
        openStatus: 'waiting',
        wishList: false,
        image: '/images/Rectangle 6189.svg',
        createdUser: '김철수',
        createdUserProfileImg: '',
    },
    {
        id: 3,
        title: '같이 공연 가요',
        location: '부산',
        date: Date.now() + 1000 * 60 * 60 * 24 * 7,
        deadline: Date.now() + 1000 * 60 * 60 * 24 * 5,
        currentPerson: 1,
        maxPerson: 3,
        openStatus: 'waiting',
        wishList: false,
        image: '/images/Rectangle 6189.svg',
        createdUser: '김철수',
        createdUserProfileImg: '',
    },
    {
        id: 4,
        title: '같이 공연 가요',
        location: '부산',
        date: Date.now() + 1000 * 60 * 60 * 24 * 7,
        deadline: Date.now() + 1000 * 60 * 60 * 24 * 5,
        currentPerson: 1,
        maxPerson: 3,
        openStatus: 'waiting',
        wishList: false,
        image: '/images/Rectangle 6189.svg',
        createdUser: '김철수',
        createdUserProfileImg: '',
    },
    {
        id: 5,
        title: '같이 공연 가요',
        location: '부산',
        date: Date.now() + 1000 * 60 * 60 * 24 * 7,
        deadline: Date.now() + 1000 * 60 * 60 * 24 * 5,
        currentPerson: 1,
        maxPerson: 3,
        openStatus: 'waiting',
        wishList: false,
        image: '/images/Rectangle 6189.svg',
        createdUser: '김철수',
        createdUserProfileImg: '',
    },
];
