import { Card } from '@/types/card';

export const mockCards: Card[] = [
    {
        articleId: 1,
        title: '같이 공연 가요',
        location: '부산',
        date: Date.now() + 1000 * 60 * 60 * 24 * 7,
        deadLine: Date.now() + 1000 * 60 * 60 * 24 * 5,
        createdAt: Date.now() + 1000 * 60 * 60 * 24 * 7,
        currentPerson: 1,
        maxPerson: 3,
        openStatus: 'waiting',
        wishList: false,
        image: '/images/Rectangle 6189.svg',
        createUser: '김철수',
        createUserProfileImg: '',
        useStatus: 'UPCOMING',
    },
    {
        articleId: 2,
        title: '같이 공연 가요',
        location: '부산',
        date: Date.now() + 1000 * 60 * 60 * 24 * 7,
        deadLine: Date.now() + 1000 * 60 * 60 * 24 * 5,
        createdAt: Date.now() + 1000 * 60 * 60 * 24 * 7,
        currentPerson: 1,
        maxPerson: 3,
        openStatus: 'waiting',
        wishList: false,
        image: '/images/Rectangle 6189.svg',
        createUser: '김철수',
        createUserProfileImg: '',
        useStatus: 'UPCOMING',
    },
    {
        articleId: 3,
        title: '같이 공연 가요',
        location: '부산',
        date: Date.now() + 1000 * 60 * 60 * 24 * 7,
        deadLine: Date.now() + 1000 * 60 * 60 * 24 * 5,
        createdAt: Date.now() + 1000 * 60 * 60 * 24 * 7,
        currentPerson: 1,
        maxPerson: 3,
        openStatus: 'waiting',
        wishList: false,
        image: '/images/Rectangle 6189.svg',
        createUser: '김철수',
        createUserProfileImg: '',
        useStatus: 'UPCOMING',
    },
    {
        articleId: 4,
        title: '같이 공연 가요',
        location: '부산',
        date: Date.now() + 1000 * 60 * 60 * 24 * 7,
        deadLine: Date.now() + 1000 * 60 * 60 * 24 * 5,
        createdAt: Date.now() + 1000 * 60 * 60 * 24 * 7,
        currentPerson: 1,
        maxPerson: 3,
        openStatus: 'waiting',
        wishList: false,
        image: '/images/Rectangle 6189.svg',
        createUser: '김철수',
        createUserProfileImg: '',
        useStatus: 'UPCOMING',
    },
    {
        articleId: 5,
        title: '같이 공연 가요',
        location: '부산',
        date: Date.now() + 1000 * 60 * 60 * 24 * 7,
        deadLine: Date.now() + 1000 * 60 * 60 * 24 * 5,
        createdAt: Date.now() + 1000 * 60 * 60 * 24 * 7,
        currentPerson: 1,
        maxPerson: 3,
        openStatus: 'waiting',
        wishList: false,
        image: '/images/Rectangle 6189.svg',
        createUser: '김철수',
        createUserProfileImg: '',
        useStatus: 'UPCOMING',
    },
];
