export const mok = {
    totalPage: 10,
    currentPage: 1,
    data: [
        {
            article_id: 1,
            title: '나의 팬팔',
            location: '서울',
            date: '1748933344',
            deadline: '1748933344',
            created_at: '1748933344',
            current_person: 1,
            max_person: 10,
            openStatus: 'waiting',
            wish_list: true,
            image: 'https://picsum.photos/200/300',
            useStatus: 'schedule',
        },
        {
            article_id: 2,
            title: '나의 팬팔',
            location: '서울',
            date: '1748933344',
            deadline: '1748933344',
            created_at: '1748933344',
            current_person: 1,
            max_person: 10,
            openStatus: 'finished',
            wish_list: true,
            image: 'https://picsum.photos/200/300',
            useStatus: 'done',
        },
        {
            article_id: 3,
            title: '나의 팬팔',
            location: '서울',
            date: '1748933344',
            deadline: '1748933344',
            created_at: '1748933344',
            current_person: 1,
            max_person: 10,
            openStatus: 'progressing',
            wish_list: true,
            image: 'https://picsum.photos/200/300',
            useStatus: 'schedule',
        },
        {
            article_id: 4,
            title: '나의 팬팔',
            location: '서울',
            date: '1748933344',
            deadline: '1748933344',
            created_at: '1748933344',
            current_person: 1,
            max_person: 10,
            openStatus: 'canceled',
            wish_list: true,
            image: 'https://picsum.photos/200/300',
            useStatus: 'schedule',
        },
    ],
};

export const mok2 = {
    totalPage: 10,
    currentPage: 1,
    data: [
        {
            article_id: 1,
            title: '나의 팬팔',
            location: '서울',
            date: '1748933344',
            deadline: '1748933344',
            created_at: '1748933344',
            current_person: 3,
            max_person: 10,
            openStatus: 'waiting',
            wish_list: true,
            image: 'https://picsum.photos/200/300',
            useStatus: 'schedule',
        },

        {
            article_id: 2,
            title: '나의 팬팔',
            location: '서울',
            date: '1748933344',
            deadline: '1748933344',
            created_at: '1748933344',
            current_person: 5,
            max_person: 10,
            openStatus: 'finished',
            wish_list: false,
            image: 'https://picsum.photos/200/300',
            useStatus: 'schedule',
        },

        {
            article_id: 3,
            title: '나의 팬팔',
            location: '서울',
            date: '1748933344',
            deadline: '1748933344',
            created_at: '1748933344',
            current_person: 7,
            max_person: 10,
            openStatus: 'progressing',
            wish_list: true,
            image: 'https://picsum.photos/200/300',
            useStatus: 'schedule',
        },
        {
            article_id: 4,
            title: '나의 팬팔',
            location: '서울',
            date: '1748933344',
            deadline: '1748933344',
            created_at: '1748933344',
            current_person: 10,
            max_person: 10,
            openStatus: 'progressing',
            wish_list: false,
            image: 'https://picsum.photos/200/300',
            useStatus: 'schedule',
        },
    ],
};
